fakeApi:
  url: https://fakestoreapi.com

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:54331/postgres
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        "[format_sql]": true
        packages-to-scan: ferreira.infra.entities

server:
  port: 8080
